# Site settings
title: LA Lights
email: joshferrara@gmail.com
url: https://lalightsband.com
description: "An indie rock band from Baton Rouge, Louisiana. Active from 2005 to 2006."
baseurl: "/la-lights"

# Color settings
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: LA Lights

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: soundcloud
    url: https://soundcloud.com/la-lights-band/albums

# Build settings
markdown: kramdown
permalink: pretty
